markdown: redcarpet
pygments: true
paginate: 15

safe:  false

#Site config
title: Jekyll Theme
description: Just another Jekyll theme design and code by zous.me.
keywords: Jekyll Theme
url: 
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: 邹帅
    email: zoushuai518@gmail.com
    imageLink: https://avatars0.githubusercontent.com/u/5516045?v=3&s=460
    simpleIntro: 我是「邹帅」，目前从事php开发！
    basename: zous.me
    baseurl: http://zous.me
    detailIntro:
      <p>Jekyll 是一个简洁的、特别针对博客平台的 静态网站 生成器。它使用一个模板目录作为网站布局的基础框架，并在其上运行 Textile 、 Markdown 或 Liquid 标记语言的转换器，最终生成一个完整的静态Web站点，可以被放置在Apache或者你喜欢的其他任何Web服务器上。它同时也是 GitHub Pages 、一个由 GitHub 提供的用于托管项目主页或博客的服务，在后台所运行的引擎。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/luoyoo/home
  - class: icon-github-alt
    url: https://github.com/zoushuai518
  - class: icon-twitter
    url: https://twitter.com/zoushuai518

#Links
customLinks:
  - item:
    - text: jz-code
      url: http://zous.me
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://zous.me/themes.html
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#comment config
disqus:
  config: true
  id: codemadman

duoshuo:
  config: false
  id: codemadman
